---

- name: services undependencies
  service: >
    name={{ item }}
    state=stopped
    enabled=no
  with_items:
    - exim4
  register: command_result
  failed_when: command_result|failed and ('service not found' not in command_result.msg) and ('no service or tool found' not in command_result.msg)
  sudo: yes

- name: packages undependencies
  apt: >
    name={{ item }}
    state=absent
    purge=yes
  with_items:
    - exim4
    - exim4-base
    - exim4-config
    - exim4-daemon-light
  sudo: yes

- name: packages dependencies
  apt: >
    name={{ item }}
    state=latest
  with_items:
    - ruby-dev
    - libsqlite3-dev
  sudo: yes

- name: packages dependency i18n
  gem: >
    name=i18n
    version=0.6.11
    state=present
    user_install=no
  sudo: yes

- name: packages
  gem: >
    name={{ item }}
    state=present
    user_install=no
  with_items:
    - mailcatcher
  sudo: yes
